# .github/workflows/ci.yml

name: 'PolyVibe CLI'

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

permissions:
  contents: 'read'

defaults:
  run:
    shell: 'bash'

env:
  SHELLCHECK_VERSION: '0.11.0'

jobs:
  #
  # Lint: Javascript
  #
  lint_javascript:
    name: 'Lint (JavaScript)'
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v4'
        with:
          fetch-depth: 1

      - name: 'Set up Node.js'
        uses: 'actions/setup-node@v4'
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
          cache-dependency-path: 'package-lock.json'

      - name: 'Install dependencies'
        run: |-
          npm ci --prefer-offline --no-audit --progress=false

      - name: 'Run formatter check'
        run: |-
          npm run format
          git diff --exit-code

      - name: 'Run linter'
        run: |-
          npm run lint:ci

      - name: 'Build project'
        run: |-
          npm run build

      - name: 'Run type check'
        run: |-
          npm run typecheck

  #
  # Lint: Shell
  #
  lint_shell:
    name: 'Lint (Shell)'
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v4'
        with:
          fetch-depth: 1

      - name: 'Install shellcheck'
        run: |-
          mkdir -p "${RUNNER_TEMP}/shellcheck"
          curl -sSLo "${RUNNER_TEMP}/.shellcheck.txz" "https://github.com/koalaman/shellcheck/releases/download/v${SHELLCHECK_VERSION}/shellcheck-v${SHELLCHECK_VERSION}.linux.x86_64.tar.xz"
          tar -xf "${RUNNER_TEMP}/.shellcheck.txz" -C "${RUNNER_TEMP}/shellcheck" --strip-components=1
          echo "${RUNNER_TEMP}/shellcheck" >> "${GITHUB_PATH}"

      - name: 'Run shellcheck'
        run: |-
          git ls-files | grep -E '^([^.]+|.*\.(sh|zsh|bash))$' | grep -v '^node_modules/' | grep -v '^integration-tests/terminal-bench/ci-tasks/' | xargs -r file --mime-type \
            | grep "text/x-shellscript" | awk '{ print substr($1, 1, length($1)-1) }' \
            | xargs -r shellcheck \
              --check-sourced \
              --enable=all \
              --exclude=SC2002,SC2129,SC2310 \
              --severity=style \
              --format=gcc \
              --color=never || true
